name: Build and Test

on:
  # push:
  #   branches:
  #     - '**'
  #   tags:
  #     - '**'
  # pull_request:
  workflow_dispatch:
    inputs:
      manual:
        description: Manual run (bypass default conditions)
        type: boolean
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'  # Set the desired Go version

      - name: Set environment variables
        shell: bash
        run: |
          echo 'GOTAGS=${{ matrix.gotags }}' >> $GITHUB_ENV
          echo 'BUILD_FLAGS=${{ matrix.build_flags }}' >> $GITHUB_ENV
          echo 'BUILD_ARGS=${{ matrix.build_args }}' >> $GITHUB_ENV
          if [[ "${{ matrix.goarch }}" != "" ]]; then echo 'GOARCH=${{ matrix.goarch }}' >> $GITHUB_ENV ; fi
          if [[ "${{ matrix.cgo }}" != "" ]]; then echo 'CGO_ENABLED=${{ matrix.cgo }}' >> $GITHUB_ENV ; fi

      - name: Install Libraries on Linux
        shell: bash
        run: |
          sudo modprobe fuse
          sudo chmod 666 /dev/fuse
          sudo chown root:$USER /etc/fuse.conf
          sudo apt-get install fuse3 libfuse-dev rpm pkg-config
        if: matrix.os == 'ubuntu-latest'

      - name: Build rclone
        run: |
          make rclone
          mkdir -p ${{ runner.workspace }}/bin
          GOPATH="${{ runner.workspace }}/go" make rclone  # Set GOPATH temporarily
          cp ${{ runner.workspace }}/go/bin/rclone* ${{ runner.workspace }}/bin  # Copy the binaries
        env:
          GO111MODULE: on

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rclone-binaries
          path: ${{ runner.workspace }}/bin

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'  # Set the desired Go version

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: rclone-binaries
          path: bin
