name: Build rclone for Windows

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Install build dependencies
        run: make build_dep

      - name: Build rclone for Windows
        run: make rclone

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rclone-windows
          path: ${{ env.GOPATH }}/bin/rclone.exe

      - name: Set environment variables
        run: echo "RCLONE_VERSION=$(make version)" >> $GITHUB_ENV

